### ISSUE TITLE
Regression in v11.3.0+: diagnostics_channel.channel is not a function in browser environment

### ISSUE THREAD

**Issue by BlackRam-oss** [isaacs/node-lru-cache#401]
After upgrading `lru-cache` from versions prior to 11.3.0 to 11.3.x (tested with 11.3.5), I encounter the following runtime error in a browser environment:

```
Uncaught TypeError: (0 , import_browser_external_diagnostics_channel.channel) is not a function
```

This occurs while developing a browser-based game library ("pixi-vn") using Vite.js. The issue does not appear in versions before 11.3.0, suggesting a regression or a change related to `diagnostics_channel` compatibility in browser builds.

Steps to reproduce:

* Use Vite.js in a browser project
* Install `lru-cache@11.3.5`
* Import and use the library in the client bundle

Expected behavior:

* The library should work correctly in browser environments as in previous versions.

Actual behavior:

* Runtime error related to `diagnostics_channel.channel` not being a function.

**Comment by isaacs** [comment]
According to vite's docs, the `browser` export condition should be favored when building for the browser. In the `browser` import condition, you'd find a `./diagnostics-channel.js` containing only this:

```js
const dummy = { hasSubscribers: false };
export const metrics = dummy;
export const tracing = dummy;
```

So, for some reason, your vite build is trying to load a node file to build for the browser. Try setting your `resolve.conditions` in your vite configuration to `['browser', 'import']`.
